version: '3.8'

services:
  mqttlogger:
    image: sosnus15/mqttlogger
    container_name: mqttlogger_container
    restart: always
    environment:
      V_BROKER: "10.10.10.210"
      # V_DB_PATH: "/var/mqttlogger/mqtt-logs/"
    volumes:
        - /home/recomputer/agroworkspace/agrostackdata/mqttlogger/:/var/mqttlogger/