name: Docker Image CI
# name: ghcr.io/sosnus/mqttlogger CI/CD
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file src/Dockerfile --tag my-image-name:$(date +%s)
